
DROP FUNCTION IF EXISTS JAVA_CURRENT_TIME_MILLIS; 
DELIMITER $$
CREATE FUNCTION JAVA_CURRENT_TIME_MILLIS() RETURNS BIGINT
BEGIN
    DECLARE NOW_TIME BIGINT;
    SET NOW_TIME = UNIX_TIMESTAMP(NOW())*1000;
    RETURN NOW_TIME;
END $$
DELIMITER ;


DROP FUNCTION IF EXISTS JAVA_TIME_STAMP_TO_DATE_STRING;
DELIMITER $$
CREATE FUNCTION JAVA_TIME_STAMP_TO_DATE_STRING(MILLIS BIGINT,PATTERN VARCHAR(50)) RETURNS VARCHAR(100)
BEGIN
    DECLARE TEMP_VAR VARCHAR(100);
    DECLARE TEMP_PATTERN VARCHAR(50);
    SET TEMP_PATTERN = IFNULL(PATTERN,'%Y-%m-%d %H:%i:%S');
    SET TEMP_VAR = FROM_UNIXTIME(MILLIS/1000, TEMP_PATTERN);
    RETURN TEMP_VAR;
END $$
DELIMITER ;


DROP FUNCTION IF EXISTS DATE_STRING_TO_JAVA_TIME_STAMP;
DELIMITER $$
CREATE FUNCTION DATE_STRING_TO_JAVA_TIME_STAMP(DATE_STRING VARCHAR(50))
RETURNS BIGINT
BEGIN
    DECLARE TEMP_VAR BIGINT;
    SET TEMP_VAR = UNIX_TIMESTAMP(DATE_STRING)*1000;
    RETURN TEMP_VAR;
END $$
DELIMITER ;