DROP TABLE IF EXISTS EKB_T_NTV_MESSAG_MSG;

CREATE TABLE EKB_T_NTV_MESSAG_MSG
(
   ID                   VARCHAR(32) NOT NULL COMMENT '主键',
   V_TPID               VARCHAR(32) NOT NULL COMMENT '招标项目ID',
   V_SENDER_NAME        VARCHAR(300) COMMENT '消息发送者姓名',
   V_MESSAGE_CONTENT    VARCHAR(4000) COMMENT '消息/命令内容',
   N_SEND_TIME          BIGINT COMMENT '发送的时间戳',
   PRIMARY KEY (ID)
);

ALTER TABLE EKB_T_IM_MSG COMMENT '云视睿博即时聊天信息表';
