ALTER TABLE EKB_T_SECTION_INFO ADD COLUMN V_JSON_OBJ LONGTEXT NULL COMMENT '扩展信息' AFTER V_CREATE_USER;
ALTER TABLE EKB_T_TENDER_PROJECT_INFO ADD COLUMN V_JSON_OBJ LONGTEXT NULL COMMENT '扩展信息' AFTER V_CREATE_USER;

