ALTER TABLE EKB_T_TENDER_PROJECT_INFO CHANGE V_TENDER_PROJECT_NAME V_TENDER_PROJECT_NAME VARCHAR(400) NULL  COMMENT '招标项目名称';
ALTER TABLE EKB_T_TENDER_PROJECT_INFO ADD COLUMN V_BID_SECTION_ID VARCHAR(32) NULL COMMENT '对应的标段编号,房建市政专用' AFTER V_TENDER_PROJECT_CODE;
ALTER TABLE EKB_T_IM_ROOM CHANGE V_TENDER_PROJECT_ID V_TPID VARCHAR(50) NULL  COMMENT '招标项目ID';

