/* 是否结束过评标 2018-4-2 09:51:21 */
ALTER TABLE EKB_T_SECTION_INFO ADD COLUMN N_IS_END_EVALUATION INT(1) DEFAULT 0 COMMENT '是否结束过评标--评标使用' AFTER N_LOW_PRICE;

/* 新增开标操作日志表*/
ALTER TABLE EKB_T_OPERATION_LOG COMMENT '开标操作日志表';

CREATE TABLE EKB_T_OPERATION_LOG
(
   ID                   	VARCHAR(32) NOT NULL COMMENT 'ID',
   V_TPID                   VARCHAR(32) NOT NULL COMMENT '招标项目ID',
   V_TENDER_PROJECT_NAME    VARCHAR(300) NOT NULL COMMENT '招标项目名称',
   V_BIDOPEN_TIME       	VARCHAR(32) NOT NULL COMMENT '开标时间',
   V_OPERATION_MEMO     	VARCHAR(300) NOT NULL COMMENT '操作说明',
   V_SOURCE_VALUE    		VARCHAR(100) NOT NULL COMMENT '源值',
   V_FINAL_VALUE        	VARCHAR(100) COMMENT '目标值',
   N_OPERATION_TIME         BIGINT COMMENT '操作时间',
   V_OPERATION_USER       	VARCHAR(100) COMMENT '操作人',
   PRIMARY KEY (ID)
);

/* 新增后台管理员操作日志菜单 */
INSERT INTO t_sys_func_info (FUNC_ID, FUNC_CODE, FUNC_NAME, FUNC_TYPE, HTTP_URL, FUNC_ICON, ORDER_KEY, IS_LEAF, IS_AVAILABLE, PARENT_ID, FUNC_MEMO)
VALUES('bfa7a74b24fa457d8e2a79a67880fbc3','0012','开标操作日志管理','1',NULL,NULL,'1','0','1',NULL,'开标操作日志管理');

INSERT INTO t_sys_func_info (FUNC_ID, FUNC_CODE, FUNC_NAME, FUNC_TYPE, HTTP_URL, FUNC_ICON, ORDER_KEY, IS_LEAF, IS_AVAILABLE, PARENT_ID, FUNC_MEMO)
VALUES('d04a19f2896b497abd51ce1c60742bfe','00120001','开标操作日志查看','1','view/eokb/bus/bidlog/bid.operation.log.html',NULL,'1','1','1','bfa7a74b24fa457d8e2a79a67880fbc3','开标操作日志查看');

/* 经确认，去除同步信用分修改 */
ALTER TABLE EKB_T_DECRYPT_INFO DROP COLUMN N_SYNC_CREDITSCORE;
ALTER TABLE EKB_T_TENDER_LIST DROP COLUMN N_SYNC_CREDITSCORE;
