/** 新增同步信用分字段 */
ALTER TABLE EKB_T_DECRYPT_INFO ADD COLUMN N_SYNC_CREDITSCORE FLOAT COMMENT '同步信用分' AFTER N_CREDITSCORE;
ALTER TABLE EKB_T_TENDER_LIST ADD COLUMN N_SYNC_CREDITSCORE FLOAT COMMENT '同步信用分' AFTER N_CREDITSCORE;

