/**新增手机版菜单**/
ALTER TABLE EKB_T_FLOW_NODE_INFO ADD COLUMN V_MOBILE_NODE_ICON VARCHAR(255) COMMENT '手机版节点图标';
ALTER TABLE EKB_T_FLOW_NODE_INFO ADD COLUMN V_MOBILE_TENDERER_PAGE_URL VARCHAR(255) COMMENT '手机版招标人页面URL';
ALTER TABLE EKB_T_FLOW_NODE_INFO ADD COLUMN V_MOBILE_BIDDER_PAGE_URL VARCHAR(255) COMMENT '手机版投标人页面URL';

/**修改流程视图**/
DROP VIEW IF EXISTS ekb_v_tender_project_flow_info;
CREATE VIEW ekb_v_tender_project_flow_info AS
SELECT 
  flow.ID AS V_FLOW_ID,
  flow.V_FLOW_CODE AS V_FLOW_CODE,
  flow.V_FLOW_NAME AS V_FLOW_NAME,
  flow.V_BEM_CODE AS V_BEM_CODE,
  flow.N_IS_SECTION_GROUP AS N_IS_SECTION_GROUP,
  node.ID AS V_NODE_ID,
  node.V_NODE_NAME AS V_NODE_NAME,
  node.V_NODE_ICON AS V_NODE_ICON,
  node.N_INDEX AS N_INDEX,
  node.N_DEPTH AS N_DEPTH,
  node.V_PID AS V_PID,
  node.V_TENDERER_PAGE_URL AS V_TENDERER_PAGE_URL,
  node.N_TENDERER_IS_SHOW AS N_TENDERER_IS_SHOW,
  node.V_BIDDER_PAGE_URL AS V_BIDDER_PAGE_URL,
  node.N_BIDDER_IS_SHOW AS N_BIDDER_IS_SHOW,
  node.N_IS_START_UP_NODE AS N_IS_START_UP_NODE,
  node.V_MOBILE_NODE_ICON,
  node.V_MOBILE_TENDERER_PAGE_URL,
  node.V_MOBILE_BIDDER_PAGE_URL,
  tp_node.ID AS ID,
  tp_node.V_TPID AS V_TPID,
  tp_node.N_STATUS AS N_STATUS,
  tp_node.N_CREATE_TIME AS N_CREATE_TIME,
  tp_node.V_CREATE_USER AS V_CREATE_USER 
FROM
  ekb_t_flow_info flow 
  JOIN ekb_t_flow_node_info node 
    ON (flow.ID = node.V_FLOW_ID) 
  LEFT JOIN ekb_t_tender_project_flow_node_info tp_node 
    ON (node.ID = tp_node.V_FLOW_NODE_ID)