ALTER TABLE EKB_T_SECTION_INFO ADD COLUMN N_PACKAGE_PRICE DOUBLE(19,4) NULL COMMENT '发包价' AFTER N_CONTROL_MIN_PRICE, ADD COLUMN N_LOW_PRICE DOUBLE(19,4) NULL COMMENT '合理低价' AFTER N_PACKAGE_PRICE, CHANGE N_CONTROL_MIN_PRICE N_CONTROL_MIN_PRICE DOUBLE(19,4) NULL COMMENT '最低限价（控制价下限）';


