/* 最新控制价发布时间*/
ALTER TABLE EKB_T_SECTION_INFO ADD COLUMN V_CONTROLPRICE_ISSUETIME VARCHAR(50) DEFAULT NULL COMMENT '最新控制价发布时间';
/* 投递标新增硬盘序列号*/
ALTER TABLE EKB_T_TBIMPORTBIDDING ADD COLUMN V_DISKID VARCHAR(2000) DEFAULT NULL COMMENT '硬盘序列号' ;
/* 联系方式表新增投标人组织机构号*/
ALTER TABLE EKB_T_BIDDER_PHONE ADD COLUMN V_ORG_CODE VARCHAR(20) DEFAULT NULL COMMENT '投标人组织机构号码' ;

